version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
  database:
    image: "andresvidal/rpi3-mongodb3"
    container_name: "mongo_db"
    ports:
      - "27017-27019:27017-27019"
    volumes:
      - mongodb_data_container:/data/db
    # command: bash -c "mongod --repair && mongod"

volumes:
  mongodb_data_container: